config/routes.rb
DOnRails::Application.routes.draw do
  resources :articles do
    resources :comments
  end

  resources :portfolio_items

  devise_for :admins

  root to: "static_pages#home"

  match "/about" => "static_pages#about"
  match "/info" => "static_pages#info"
  match "/contact" => "static_pages#contact"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :body, :tags, :title, :views, :article_image, :remote_article_image_url
  mount_uploader :article_image, ImageUploader
  has_many :comments, :dependent => :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  attr_accessible :article_id, :comment, :name
end

app/models/portfolio_item.rb
class PortfolioItem < ActiveRecord::Base
  attr_accessible :description, :github, :link, :title, :portfolio_image, :remote_portfolio_image_url
  mount_uploader :portfolio_image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate_admin!, except: [:index, :show, :incPageView]
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.order("created_at DESC")
    @top3 = Article.order("views DESC").first(3)
    @article = Article.new
  end

  def show
    @article = Article.find(params[:id])
    incPageView(@article)
    @comment = Comment.new
    @comment.article_id = @article.id
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(params[:article])
    @article.views = 0
    @article.save

    flash.notice = "Successfully created '#{@article.title}'"
    redirect_to article_path(@article)
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update_attributes(params[:article])

    flash.notice = "'#{@article.title}'' updated"
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    flash.notice = "Successfully deleted '#{@article.title}'!"
    redirect_to articles_path
  end

  def incPageView(article)
    article.views += 1
    article.update_attributes(params[:views])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(params[:comment])
    @comment.article_id = params[:article_id]

    @comment.save

    redirect_to article_path(@comment.article)
  end
end

app/controllers/portfolio_items_controller.rb
class PortfolioItemsController < ApplicationController
  before_filter :authenticate_admin!, except: [:index]
  # GET /portfolio_items
  # GET /portfolio_items.json
  def index
    @portfolio_items = PortfolioItem.all

    respond_to do |format|
      format.html 
      format.json { render json: @portfolio_items }
    end
  end

  # GET /portfolio_items/1
  # GET /portfolio_items/1.json
  def show
    @item = PortfolioItem.find(params[:id])

    respond_to do |format|
      format.html 
      format.json { render json: @item }
    end
  end

  # GET /portfolio_items/new
  # GET /portfolio_items/new.json
  def new
    @portfolio_item = PortfolioItem.new

    respond_to do |format|
      format.html 
      format.json { render json: @portfolio_item }
    end
  end

  # GET /portfolio_items/1/edit
  def edit
    @portfolio_item = PortfolioItem.find(params[:id])
  end

  # POST /portfolio_items
  # POST /portfolio_items.json
  def create
    @portfolio_item = PortfolioItem.new(params[:portfolio_item])

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to @portfolio_item, notice: 'Portfolio item was successfully created.' }
        format.json { render json: @portfolio_item, status: :created, location: @portfolio_item }
      else
        format.html { render action: "new" }
        format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /portfolio_items/1
  # PUT /portfolio_items/1.json
  def update
    @portfolio_item = PortfolioItem.find(params[:id])

    respond_to do |format|
      if @portfolio_item.update_attributes(params[:portfolio_item])
        format.html { redirect_to @portfolio_item, notice: 'Portfolio item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolio_items/1
  # DELETE /portfolio_items/1.json
  def destroy
    @portfolio_item = PortfolioItem.find(params[:id])
    @portfolio_item.destroy

    respond_to do |format|
      format.html { redirect_to portfolio_items_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def info
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Give full title in browser
  def full_title(page_title)
    base_title = "Donald on Rails"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/portfolio_items_helper.rb
module PortfolioItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/articles/_comment.html.haml
%h4= "Comment by #{comment.name}"
%p.comment= comment.comment
%small.pull-right= "Posted #{distance_of_time_in_words(comment.created_at,Time.now)} ago"
%br
%hr

app/views/articles/_form.html.haml
.row
  .span5.offset2   
    = form_for @article, html: { multipart: true } do |f|
      - if @article.errors.any?
        %ul.alert.alert-error.alert-block.unstyled
          %h4.text-left= "Form contains #{pluralize(@article.errors.count, "error")}"
          %br
          - @article.errors.full_messages.each do |error|
            %li.text-left= error

      %p= f.text_field :title, placeholder: "Title", style: "width:100%"
      
      %p= f.text_area :body, placeholder: "Body. You may use html tags such as <p>", style: "width:100%"
      
      %p= f.text_field :tags, placeholder: "comma seperated tags", style: "width:100%"
      
      %p= f.file_field :article_image

      %p= f.text_field :remote_article_image_url, placeholder: "Image URL"

      = f.submit "Create new article", class: "btn btn-inverse" 

app/views/articles/edit.html.haml
%h1 Editing article

= render 'form'

= link_to 'Show', @article 
= link_to 'Back', articles_path

app/views/articles/index.html.haml
- if admin_signed_in?
  = link_to "New article?", new_article_path, class: "btn btn-inverse pull-right"

- if @top3.count == 3
  %h3 The Most Popular Articles
  .row
    .span12
      %ul.thumbnails
        - @top3.each do |article| 
          %li.span4
            .thumbnail
              %p.top3
                = link_to image_tag(article.article_image_url(:thumb), class: "pic"), article_path(article)
              = link_to article.title, article_path(article)
              %p= "Viewed #{pluralize(article.views, 'time')}"
          
%h3 Recent Articles

.row
  .span12
    %ul.thumbnails
      - @articles.each do |article|
        %li.span4
          .thumbnail
            %p.top3
              = link_to image_tag(article.article_image_url(:thumb).to_s, class: "pic"), article_path(article)
            = link_to article.title, article_path(article)
            %p= "Viewed #{pluralize(article.views, 'time')}"

app/views/articles/new.html.haml
%h1 New article

= render 'form'
= link_to 'Back', articles_path

app/views/articles/show.html.haml
= provide :title, @article.title
.row
  .span6.offset2
    %h2= @article.title

    .center= image_tag(@article.article_image_url(:article), style: "width:100%; border-radius:4px")
    %br

    %p= raw(@article.body)
    %p= @article.tags


    - if admin_signed_in?
      = link_to 'Edit', edit_article_path(@article), class: "btn btn-warning"
      = link_to 'Delete', article_path(@article), method: :delete, class: "btn btn-danger", confirm: "Are you sure?"
    = link_to 'Back', article_path, class: "btn btn-inverse" 


    = render partial: 'comments/form'
    %h3= "Comments (#{@article.comments.size})"
    %hr
    = render partial: 'articles/comment', collection: @article.comments

app/views/comments/_form.html.haml
%h3 Post a Comment
= form_for [ @article, @comment ] do |f|
  %p
    = f.text_field :name, placeholder: "Your name", style: "width:100%"
  %p
    = f.text_area :comment, placeholder: "Your comment", style: "width:100%; height: 200px" 
  %p
    = f.submit 'Submit', class: "btn btn-inverse"

app/views/layouts/_footer.html.haml
%footer.footer
  %nav
    %ul
      %li.pull-left= link_to "Built with Ruby on Rails, hosted by Digital Ocean", "https://www.digitalocean.com/?refcode=0e7d22b46b53"
      %li.pull-right= link_to "About", about_path
      %li.pull-right= link_to "Contact", contact_path

app/views/layouts/_navbar.html.haml
.navbar
  .navbar-inner
    .brand= link_to "Donald on Rails", root_path, id: "logo"
    %nav
      %ul.nav.pull-right
        %li= link_to "About", about_path
        %li= link_to "Portfolio", portfolio_items_path
        %li= link_to "Blog", articles_path 
        %li= link_to "Contact", contact_path
        - if admin_signed_in?
          %li= link_to "Not #{current_admin.email}? Logout", destroy_admin_session_path, method: :delete
          %li= link_to 'Edit profile', edit_admin_registration_path 

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= full_title(yield(:title)) 
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    .container
      %br
      
      = render partial: "layouts/navbar"

      - flash.each do |key, value|
        .alert.box{ class: "alert-#{key}"}
          %strong
            = value
          %a.close{ :data => { :dismiss => "alert" }}x
          
      
      = yield

      = render partial: "layouts/footer"

      = debug(params) if Rails.env.development?

app/views/portfolio_items/_form.html.haml
.row
  .span5.offset2   
    = form_for @portfolio_item, html: { multipart: true } do |f|
      - if @portfolio_item.errors.any?
        %ul.alert.alert-error.alert-block.unstyled
          %h4.text-left= "Form contains #{pluralize(@portfolio_item.errors.count, "error")}"
          %br
          - @portfolio_item.errors.full_messages.each do |error|
            %li.text-left= error

      %p= f.text_field :title, placeholder: "Title", style: "width:100%"
      
      %p= f.text_area :description, placeholder: "Description", style: "width:100%"
      
      %p= f.text_field :link, placeholder: "Link to site", style: "width:100%"
      
      %p= f.text_field :github, placeholder: "Github link", style: "width:100%"
      
      %p= f.file_field :portfolio_image

      %p= f.text_field :remote_portfolio_image_url, placeholder: "Image URL"

      = f.submit "Create new item", class: "btn btn-inverse" 

app/views/portfolio_items/edit.html.haml
%h1 Editing Portfolio item

= render 'form'

= link_to 'Show', @portfolio_item 
= link_to 'Back', portfolio_items_path 

app/views/portfolio_items/index.html.haml
=provide :title, "Portfolio"

- @portfolio_items.each do |item|
  .row
    %hr.featurette-divider
    .featurette
      = image_tag item.portfolio_image_url(:thumb).to_s, class: "featurette-image pull-right portfolio-img"
      %h2.featurette-heading.text-left= item.title
      %p.lead= item.description
      - unless item.github == ""
        = link_to "view source code", item.github, class: "btn btn-inverse"
      - unless item.link == ""  
        = link_to "view site", item.link, class: "btn btn-inverse"    
      - if admin_signed_in?
        = link_to "Edit", edit_portfolio_item_path(item), class: "btn btn-inverse"

app/views/portfolio_items/new.html.haml
%h1 New portfolio item

= render 'form'

= link_to 'Back', portfolio_items_path

app/views/portfolio_items/show.html.haml
.row
  %hr.featurette-divider
  .featurette
    = image_tag @item.portfolio_image_url, class: "featurette-image pull-right", style: "height:200px; width:300px"
    %h2.featurette-heading.text-left= @item.title
    %p.lead= @item.description
    = link_to "view source code", @item.github, class: "btn btn-inverse"
    = link_to "view site", @item.link, class: "btn btn-inverse"
    = link_to 'Edit', edit_portfolio_item_path(@item), class: "btn btn-inverse"
    = link_to 'Back', portfolio_items_path, class: "btn btn-inverse"

app/views/static_pages/about.html.haml
=provide(:title, "About")
%h1 About Me
%p Around one year of Ruby/Ruby on Rails Tinkering. Previous experience with HTML, CSS, Javascript, Python. Masters Degree in Chemistry with a final year project in Computational Chemistry.
%p Seeking Internship or entry-level Ruby on Rails development position. Can be found on the ground floor of the Edinburgh Techcube.

= mail_to "ddmckendrick@gmail.com", "Email", class: "btn btn-inverse"
= link_to "LinkedIn", "http://www.linkedin.com/pub/donald-mckendrick/54/65b/405", class: "btn btn-inverse"
= link_to "Twitter", "https://twitter.com/DearDonald", class: "btn btn-inverse"
= link_to "Github", "https://github.com/ddmck", class: "btn btn-inverse"

app/views/static_pages/contact.html.haml
= provide :title, "Contact"

%p If you wish to get in touch email me at ddmckendrick@gmail.com

= mail_to "ddmckendrick@gmail.com", "Open default email window", class: "btn btn-inverse"

app/views/static_pages/home.html.haml
.hero-unit
  %h1.text-right Donald McKendrick
  %h2.text-right Edinburgh based Ruby on Rails Developer 